name: ILPIASTRINO
favicon: null
layout_spectrum: 0.5988747156225145
typography_spectrum: 0.1199500011280179
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#878701'
    - '#b3aa03'
    - '#e1dbab'
    - '#fefad4'
    - '#676505'
  brandStrength: 0.0012859366834163666
  lightness: 0.45466483756899834
  saturation: 0.8358643900137395
  rhythmicContrast: 0.8185823555104434
purpose: []
